### PR TITLE
Pull request for 210101092.cpp

### PR DESCRIPTION
**Pull request by SahilDanayak**
Please grant this request

P.S. I actually thought that we had to change directly into hello.cpp file instead of copying the contents. Thus pls ignore the first two commits

### CODE REVIEW

**Comment by AmreshSinha** [comment]
Create a new file instead of editing the template file

**Review by AmreshSinha — CHANGES_REQUESTED** [review]
^

**Comment by SahilDanayak** [comment]
> Create a new file instead of editing the template file

I have already created a new file 210101092.cpp and committed the same. Should I create another pull request?

**Comment by AmreshSinha** [comment]
> > Create a new file instead of editing the template file
> 
> I have already created a new file 210101092.cpp and committed the same. Should I create another pull request?

Yeah sure

**Pull request closed without merging**
